### ISSUE TITLE
generate fr and de - 1410

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/astra-control-center-2108#5]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
@netapp-rlithman - Why has localization been disabled for this repo?

**Comment by ntap-bmegan** [comment]
No, I just tagged you since you had made the most recent update (same in a couple of others).

**Comment by ntap-bmegan** [comment]
@netapp-rlithman - For this and the other astra repos where I tagged you, someone needs to add the `harmony_enabled` keyword in project.yml for `prod` only and push, ensuring that the update is present in both the dev and public repos. Can you do that or tell me who should? 

````
prod:
    pdf_enabled: true
    harmony_enabled: true
````

**Comment by netapp-rlithman** [comment]
@ntap-bmegan - The Astra team should be able to help. 

@netapp-dbagwell, @amgrissino, and @netapp-mwallis - I'm sharing Megan's request with you. Fyi.

**Comment by ntap-bmegan** [comment]
Thanks, @netapp-rlithman! The others, which have their own issues, are 2112 and 2204. Same situation.

**Comment by netapp-rlithman** [comment]
Same situation.

**Comment by netapp-dbagwell** [comment]
Thanks @netapp-rlithman and @ntap-bmegan. Created a JIRA bug to address 2112, 2204 and 2108. I will update here when resolved.

**Comment by netapp-dbagwell** [comment]
@ntap-bmegan is before EOD Tuesday ok?

**Comment by ntap-bmegan** [comment]
@netapp-dbagwell - Yes, thanks.

**Comment by netapp-dbagwell** [comment]
2112, 2204 and 2108 updates complete. French and German sites looking very French and German.

**Comment by ntap-bmegan** [comment]
Configuration is complete. TOT: 10 min
